version: '3'
services:
  api:
    build: .
    depends_on:
      - mongoDB
    ports:
      - '9999:9999'
    expose:
      - '9999'
    networks:
      - backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
  mongoDB:
    image: mongo
    expose:
      - '27017'
    networks:
      - backend
    volumes:
      - './data:/data/db'
networks:
  backend:
